# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_apidocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidocument',
            name='document',
            field=models.FileField(upload_to='media/documents'),
        ),
    ]
