# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-05 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_auto_20181218_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='credits',
            field=models.DecimalField(decimal_places=0, default='1000', max_digits=8),
        ),
    ]
