# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-05 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0008_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credits',
            old_name='userr',
            new_name='user',
        ),
    ]
