# Generated by Django 2.1.5 on 2019-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0012_subuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='institution',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='institution',
            name='mobile_no',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='institution',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
