# Generated by Django 2.1.5 on 2019-02-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0013_auto_20190219_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='mobile_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
