# Generated by Django 2.1.5 on 2019-02-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0014_auto_20190219_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='flag',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
